export const previousImage = 'PreviousImage'
export const nextImage = 'NextImage'
export const cartAlt = 'cart'
export const currBoxAlt = 'Currency box toggle'
export const logoAlt = 'logo'
export const qtyUp = 'Add one to quantity'
export const qtyDown = 'Substract one from quantity'
export const addToCartAlt = 'Add to cart'